
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-note-list
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: yarn dev
