services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-image
    container_name: frontend-note-list
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: yarn dev
    # atau jika perlu: command: yarn run dev

volumes:
  frontend_node_modules:
