services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-image
    container_name: frontend-note-list
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules       # untuk menghindari node_modules tertimpa host
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: yarn dev --port 3000
